# Generated by Django 3.1.1 on 2020-09-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16, verbose_name='关键字')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='键')),
                ('value', models.TextField(help_text='最长128字符', max_length=128, verbose_name='值')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='点击来源')),
                ('device', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备类型')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Doraemon.keyword', verbose_name='关键字')),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'db_table': 'search',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='机器人名称')),
                ('group', models.CharField(max_length=64, verbose_name='群组名称')),
                ('api', models.URLField(unique=True, verbose_name='机器人链接地址')),
                ('mode', models.CharField(choices=[('wechat', '企业微信'), ('dingtalk', '钉钉'), ('other', '其他类型')], max_length=16, verbose_name='类型')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '机器人',
                'verbose_name_plural': '机器人',
                'db_table': 'robot',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('GROUP_MORNING', '早九点值班提醒'), ('GROUP_NIGHT', '晚六点值班提醒'), ('PROBLEM_MORNING', '早九点接待提醒'), ('PROBLEM_NIGHT', '晚六点接待提醒')], max_length=32, unique=True, verbose_name='任务名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('robot', models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doraemon.robot', verbose_name='推送机器人')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='连接标题')),
                ('link', models.URLField(unique=True, verbose_name='链接地址')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='上次修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('keywords', models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='keywords_set', to='Doraemon.Keyword', verbose_name='关键字')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'db_table': 'link',
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='点击来源')),
                ('device', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备类型')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Doraemon.link', verbose_name='对应链接')),
            ],
            options={
                'verbose_name': '点击记录',
                'verbose_name_plural': '点击记录',
                'db_table': 'click',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(error_messages={'unique': '当天已存在值班人，请先移除或修改记录'}, unique=True, verbose_name='值班日期')),
                ('token', models.UUIDField(blank=True, default='6be8413bcea5458b908d5b39062514d9', unique_for_year=True, verbose_name='签到Token')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('active', models.DateTimeField(blank=True, help_text='为空则表示未签到', null=True, verbose_name='签到时间')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='点击来源')),
                ('device', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备类型')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班',
                'db_table': 'attendance',
            },
        ),
    ]
